from pydantic import BaseModel, Field
from typing import List, Optional


class Persona(BaseModel):
    name: str = Field(description="Name of the persona.")
    role: str = Field(
        description="Role or expertise of the persona (e.g., 'Hardware Optimization Expert')."
    )
    description: str = Field(
        description="Detailed description of what this persona focuses on."
    )


class PersonaList(BaseModel):
    personas: List[Persona] = Field(
        default_factory=list, description="List of generated personas."
    )


class SearchQuery(BaseModel):
    query: str = Field(description="The exact search query to execute.")
    rationale: str = Field(description="Why this query is important for the research.")


class SearchQueryList(BaseModel):
    queries: List[SearchQuery] = Field(
        default_factory=list,
        description="List of search queries generated by a persona.",
    )


class Fact(BaseModel):
    statement: str = Field(
        description="A factual statement derived from search results."
    )
    source_url: str = Field(description="The URL where this fact was found.")


class FactList(BaseModel):
    facts: List[Fact] = Field(
        default_factory=list, description="List of extracted facts."
    )


class Section(BaseModel):
    title: str = Field(description="Title of the section.")
    content: str = Field(
        description="Markdown content of the section, heavily citing the sources."
    )


class Reference(BaseModel):
    id: int = Field(description="The citation number, e.g., 1")
    title: str = Field(description="A short descriptive title for the reference")
    url: str = Field(description="The URL of the source")


class ResearchReport(BaseModel):
    title: str = Field(description="Title of the overall research report.")
    sections: List[Section] = Field(
        default_factory=list, description="Sections of the report."
    )
    references: List[Reference] = Field(
        default_factory=list,
        description="A structured list of all references cited in the report using [1], [2] format.",
    )


class CriticFeedback(BaseModel):
    actionable_issues: bool = Field(
        description="True if there are critical issues requiring revision, False if the report is acceptable."
    )
    feedback: str = Field(
        description="Specific feedback on what needs to be improved. Empty if no issues."
    )


class OutlineSection(BaseModel):
    title: str = Field(description="Title of the section.")
    description: str = Field(
        description="Brief description of what should be covered in this section based on the gathered facts."
    )


class Outline(BaseModel):
    title: str = Field(description="Title of the overall report.")
    sections: List[OutlineSection] = Field(
        default_factory=list, description="List of sections in the outline."
    )
